version: '3.3'

services:

    web:
        image: ${WEB_CONTAINER_IMAGE:-api-mmpi/web}
        container_name: ${WEB_CONTAINER_NAME:-api-mmpi-web}
        build:
            context: web
            args:
                XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST}
                               remote_port=9000
                               remote_enable=On
                               remote_autostart=On
                PHP_IDE_CONFIG: serverName=${XDEBUG_SERVER_NAME}
        ports:
            - ${WEB_CONTAINER_IP}:${WEB_CONTAINER_SSH_PORT:-22}:22
            - ${WEB_CONTAINER_IP}:${WEB_CONTAINER_HTTP_PORT:-80}:80
            - ${WEB_CONTAINER_IP}:${WEB_CONTAINER_HTTPS_PORT:-443}:443
            - ${WEB_CONTAINER_IP}:${WEB_CONTAINER_MYSQL_PORT:-3306}:3306
        volumes:
            - ${WEB_CONTAINER_SRC_VOLUME:-../.}:/enterprise/src
            - ${WEB_CONTAINER_DB_VOLUME:-../storage/db/mysql}:/enterprise/mysql-data
        working_dir: /enterprise/src
        networks:
            - local

    elastic:
        image: api-mmpi/elastic
        container_name: api-mmpi-elastic
        build:
            context: elasticsearch
        volumes:
            - ${ELASTIC_CONTAINER_DB_VOLUME:-../storage/db/elasticsearch}:/usr/share/elasticsearch/data
        networks:
            - local

networks:
    local:
        driver: bridge
